name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    - name: Run pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle exercise_1
        
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: install dependencies
      run: pip install build

      
    - name: Build package
      run: python3 -m build
    - name: Install dependencies
      run: pip install -r  file.whl
