name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Pycodestyle Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install pycodestyle

      - name: Run Pycodestyle
        run: pycodestyle exercise_1

  package:
    name: Package Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          cd exercise_1
          pip install -r requirements.txt

      - name: Build Application
        run: python3 -m build exercise_1

  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    needs: package

    strategy:
      matrix:
        test: ["test_fast.py", "test_slow_1.py", "test_slow_2.py"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # - name: Install Dependencies
      #   run: pip install -r requirements.txt
      - name: Install Dependencies
        run: |
          cd exercise_1
          pip install -r requirements.txt

      - name: Run ${{ matrix.test }}
        run: python -m unittest tests/${{ matrix.test }}

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest

  #   needs: tests

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2

  #     - name: Run Deployment Script
  #       run: ./deploy.sh
